spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888/
      request-connect-timeout: 2000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  sql:
    init:
      mode: always
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  profiles:
    active: prod


server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful
polar:
  greeting: Welcome to the local book catalog V2!


management:
  endpoints:
    web:
      exposure:
        include: refresh