apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:

      containers:
      - name: catalog-service
        image: mhacioglu/catalog-service:0.0.2-SNAPSHOT
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:  [ "sh", "-c", "sleep 5" ]
        ports:
        - containerPort: 6082
        env:
        - name: BPL_JVM_THREAD_COUNT
          value: "50"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://polar-postgres-catalog/polardb_catalog